Implement Navigation Bar
setlife-network/setlife-solutions pull request #103
Opened 2022-08-03 17:42 UTC by Ovifer13

**Issue #48**

- [ ] Create `Navbar` component
- [ ] Create `layout` component
- [ ] Import `layout` component to `_app.tsx`
- [ ] Polish Navbar

2022-08-04 15:57 UTC, Ovifer13 commented
**Implementation proof**
[Navigation Bar setlife-solutions - Watch Video](https://www.loom.com/share/24c297df583c4b2c87a3215a98578af1)

2022-08-05 03:50 UTC, sofiaromorales requested changes

2022-08-05 03:50 UTC, sofiaromorales commented on components/Navbar.tsx
> +            </div>
Convert this into a map

2022-08-05 03:50 UTC, sofiaromorales commented on components/Navbar.tsx
> +                    <span className={`h-0.5 w-full bg-solid-white rounded-lg transform transition duration-300 ease-in-out ${open ? "-rotate-45 -translate-y-3.5" : ""}`} />
Transform into its own component

2022-08-05 04:19 UTC, sofiaromorales commented
@Ovifer13 pls fix listing issues and take a look into the changes I made on the last commit.

Besides of that pls address the following changes:

1. Fix spacing on hamburger menu 
![Screen Shot 2022-08-05 at 12 17 54 AM](https://user-images.githubusercontent.com/49292858/183000506-9821f165-02a4-481a-9e53-6b78b80881d0.png)
2. On desktop the navbar has a different style
![Screen Shot 2022-08-05 at 12 18 53 AM](https://user-images.githubusercontent.com/49292858/183000615-ac68e415-afa7-41c7-a2cf-6b8ba94a4f0d.png)

2022-08-05 05:46 UTC, Ovifer13 commented
@sofiaromorales I see, Idk why I can't find where the desktop version is. I only have the mobile version and I thought It was going to be used for both.

2022-08-05 12:50 UTC, sofiaromorales commented
> @sofiaromorales I see, Idk why I can't find where the desktop version is. I only have the mobile version and I thought It was going to be used for both.

https://www.figma.com/file/KlLr27PTO7Dzz3D9CE2LzT/setlife-core?node-id=649%3A1467

On the same figma file to the left you have a panel with multiple pages

2022-08-05 16:41 UTC, sofiaromorales commented
@Ovifer13 pls fix linter bugs and have in consideration the changes I made in [c8a380d](https://github.com/setlife-network/setlife-solutions/pull/103/commits/c8a380d4be63ce320991b249a3b2270de5223aec) for future pr's

2022-08-08 15:01 UTC, Ovifer13 commented
**Implementation proof with fixes**
[Implement Navigation Bar after fixes - Watch Video](https://www.loom.com/share/48c16c748f62497bbc9c57b714c111e8)

2022-08-11 04:09 UTC, sofiaromorales approved these changes

2022-08-11 04:09 UTC, merged